import type { WeatherRecord } from "./types";
import { decodeWeatherCode } from "./weather";

/**
 * Download a text file in the browser
 */
function downloadFile(
  content: string,
  filename: string,
  mimeType: string
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export records as JSON
 */
export function exportJSON(records: WeatherRecord[]): void {
  const content = JSON.stringify(records, null, 2);
  downloadFile(content, "weather_records.json", "application/json");
}

/**
 * Export records as CSV
 */
export function exportCSV(records: WeatherRecord[]): void {
  const headers = [
    "ID",
    "Location Input",
    "Resolved Name",
    "Latitude",
    "Longitude",
    "Start Date",
    "End Date",
    "Temperature (°C)",
    "Feels Like (°C)",
    "Humidity (%)",
    "Wind Speed (km/h)",
    "Weather Condition",
    "UV Index",
    "Notes",
    "Created At",
    "Updated At",
  ];

  const escape = (val: unknown): string => {
    const str = val === null || val === undefined ? "" : String(val);
    if (str.includes(",") || str.includes('"') || str.includes("\n")) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };

  const rows = records.map((r) => {
    const cw = r.weatherJson?.current;
    const condition = cw
      ? decodeWeatherCode(cw.weatherCode, cw.isDay).label
      : "";
    return [
      r.id,
      r.locationInput,
      r.resolvedName,
      r.latitude,
      r.longitude,
      r.startDate,
      r.endDate,
      cw?.temperature ?? "",
      cw?.feelsLike ?? "",
      cw?.humidity ?? "",
      cw?.windSpeed ?? "",
      condition,
      cw?.uvIndex ?? "",
      r.notes,
      r.createdAt,
      r.updatedAt,
    ]
      .map(escape)
      .join(",");
  });

  const content = [headers.map(escape).join(","), ...rows].join("\n");
  downloadFile(content, "weather_records.csv", "text/csv;charset=utf-8;");
}

/**
 * Export records as Markdown
 */
export function exportMarkdown(records: WeatherRecord[]): void {
  const lines: string[] = [
    "# Weather Records Export",
    "",
    `**Exported at:** ${new Date().toLocaleString()}`,
    `**Total Records:** ${records.length}`,
    "",
    "---",
    "",
  ];

  for (const r of records) {
    const cw = r.weatherJson?.current;
    const condition = cw
      ? decodeWeatherCode(cw.weatherCode, cw.isDay).label
      : "N/A";

    lines.push(`## 📍 ${r.resolvedName}`);
    lines.push("");
    lines.push(`| Field | Value |`);
    lines.push(`|-------|-------|`);
    lines.push(`| **Location Input** | ${r.locationInput} |`);
    lines.push(`| **Resolved Name** | ${r.resolvedName} |`);
    lines.push(
      `| **Coordinates** | ${r.latitude.toFixed(4)}, ${r.longitude.toFixed(4)} |`
    );
    lines.push(`| **Date Range** | ${r.startDate} → ${r.endDate} |`);

    if (cw) {
      lines.push(`| **Condition** | ${condition} |`);
      lines.push(`| **Temperature** | ${cw.temperature}°C |`);
      lines.push(`| **Feels Like** | ${cw.feelsLike}°C |`);
      lines.push(`| **Humidity** | ${cw.humidity}% |`);
      lines.push(`| **Wind Speed** | ${cw.windSpeed} km/h |`);
      lines.push(`| **UV Index** | ${cw.uvIndex} |`);
    }

    if (r.notes) {
      lines.push(`| **Notes** | ${r.notes} |`);
    }
    lines.push(`| **Saved At** | ${new Date(r.createdAt).toLocaleString()} |`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  lines.push("*Generated by PM Weather AI — Built by Muhammad Ahmad*");
  lines.push(
    "*PM Accelerator: Helping aspiring product and AI builders gain practical experience.*"
  );

  downloadFile(lines.join("\n"), "weather_records.md", "text/markdown");
}

/**
 * Export records as PDF using jsPDF
 */
export async function exportPDF(records: WeatherRecord[]): Promise<void> {
  // Dynamically import jsPDF to avoid SSR issues
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });

  // Header
  doc.setFillColor(8, 15, 40);
  doc.rect(0, 0, doc.internal.pageSize.width, 60, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("PM Weather AI — Saved Records", 40, 38);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(180, 210, 255);
  doc.text(
    `Built by Muhammad Ahmad | Exported: ${new Date().toLocaleString()}`,
    40,
    52
  );

  // Table
  const headers = [
    "Location",
    "Lat/Lon",
    "Dates",
    "Temp",
    "Condition",
    "Wind",
    "UV",
    "Notes",
  ];

  const rows = records.map((r) => {
    const cw = r.weatherJson?.current;
    const condition = cw
      ? decodeWeatherCode(cw.weatherCode, cw.isDay).label
      : "N/A";
    return [
      r.resolvedName,
      `${r.latitude.toFixed(2)}, ${r.longitude.toFixed(2)}`,
      `${r.startDate}\n${r.endDate}`,
      cw ? `${cw.temperature}°C` : "N/A",
      condition,
      cw ? `${cw.windSpeed} km/h` : "N/A",
      cw ? String(cw.uvIndex) : "N/A",
      r.notes || "-",
    ];
  });

  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: 70,
    styles: {
      fontSize: 9,
      cellPadding: 6,
      textColor: [30, 30, 30],
    },
    headStyles: {
      fillColor: [12, 26, 70],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [240, 248, 255],
    },
    columnStyles: {
      7: { cellWidth: 120 },
    },
  });

  // Footer
  const pageCount = (doc.internal as any).getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      "PM Accelerator | Weather AI Assessment | Muhammad Ahmad",
      40,
      doc.internal.pageSize.height - 15
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width - 80,
      doc.internal.pageSize.height - 15
    );
  }

  doc.save("weather_records.pdf");
}
